//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotusLyncer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string settingUpdateFrequencyTextBox {
            get {
                return ((string)(this["settingUpdateFrequencyTextBox"]));
            }
            set {
                this["settingUpdateFrequencyTextBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("In a Meeting")]
        public string settingMessageTextBox {
            get {
                return ((string)(this["settingMessageTextBox"]));
            }
            set {
                this["settingMessageTextBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Undisclosed Location")]
        public string settingLocationTextBox {
            get {
                return ((string)(this["settingLocationTextBox"]));
            }
            set {
                this["settingLocationTextBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingNotesTitleCheckBox {
            get {
                return ((bool)(this["settingNotesTitleCheckBox"]));
            }
            set {
                this["settingNotesTitleCheckBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool settingNotesLocationCheckBox {
            get {
                return ((bool)(this["settingNotesLocationCheckBox"]));
            }
            set {
                this["settingNotesLocationCheckBox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("None")]
        public global::Microsoft.Lync.Model.ContactAvailability settingAvailabilityComboBox {
            get {
                return ((global::Microsoft.Lync.Model.ContactAvailability)(this["settingAvailabilityComboBox"]));
            }
            set {
                this["settingAvailabilityComboBox"] = value;
            }
        }
    }
}
